# Generated by Django 4.0.1 on 2022-02-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_author_options_alter_books_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name', 'surname'],
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name', 'surname']},
        ),
    ]
