# Generated by Django 4.0.1 on 2022-02-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_bookreaders_alter_author_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='are_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='books',
            name='readers',
            field=models.ManyToManyField(to='myapp.BookReaders'),
        ),
    ]
