# Generated by Django 4.0.1 on 2022-02-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_books_are_available_books_readers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='readers',
            field=models.ManyToManyField(null=True, to='myapp.BookReaders'),
        ),
    ]
