# Generated by Django 4.0.1 on 2022-02-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_comment_article_alter_dislike_article_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookauthor',
            options={'ordering': ['name', 'surname'], 'verbose_name_plural': 'BookAuthors'},
        ),
        migrations.AlterModelOptions(
            name='bookreaders',
            options={'ordering': ['name', 'surname'], 'verbose_name_plural': 'BookReaders'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['name'], 'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='books',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
