# Generated by Django 4.0.1 on 2022-02-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_bookauthor_options_alter_bookreaders_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
